ActvCloudSuite/ActvMvcClient/Controllers/AmountCollectionTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ActvMvcClient.Models;
using PagedList;

namespace ActvMvcClient.Controllers
{
    [Authorize]
    public class AmountCollectionTablesController : Controller
    {
        private ActvMvcClientEntities db = new ActvMvcClientEntities();

        // GET: AmountCollectionTables
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, string collectionSource)
        {
            return CommonIndex(sortOrder, currentFilter, searchString, page, collectionSource, null, null);
        }


        [HttpPost]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, string collectionSource, DateTime? from, DateTime? to)
        {
            return CommonIndex(sortOrder,currentFilter,searchString,page,collectionSource,from,to);
        }

        private ActionResult CommonIndex(string sortOrder, string currentFilter, string searchString, int? page, string collectionSource, DateTime? from, DateTime? to)
        {
            collectionSource = Enum.GetName(typeof(CollectionSourceEnum), CollectionSourceEnum.mb);
            int pageSize = 20;
            int pageNumber = (page ?? 1);

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder == "name_asc" ? "name_desc" : "name_asc";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            IQueryable<AmountCollectionTable> coll;
            //var coll = db.AmountCollectionTables.Take(20).Include(a => a.AgentDetailsTable).Include(a => a.EmployeeTable).Include(a => a.CustomerDetailsTable);
            if (from != null && to != null)
            {
                 coll = db.AmountCollectionTables.Where(act => act.CollectionSource == collectionSource && act.CollectionDate2 >= from && act.CollectionDate2 <= to).Include(a => a.AgentDetailsTable).Include(a => a.EmployeeTable).Include(a => a.CustomerDetailsTable);
            }
            else
            {
                 coll = db.AmountCollectionTables.Where(act => act.CollectionSource == collectionSource).Include(a => a.AgentDetailsTable).Include(a => a.EmployeeTable).Include(a => a.CustomerDetailsTable);

            }
            if (!String.IsNullOrEmpty(searchString))
            {
                coll = coll.Where(c => c.CustomerDetailsTable.CustomerName.Contains(searchString)
                || c.BillNum.ToString().Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    coll = coll.OrderByDescending(c => c.CustomerDetailsTable.CustomerName);
                    break;
                case "name_asc":
                    coll = coll.OrderBy(c => c.CustomerDetailsTable.CustomerName);
                    break;
                case "Date":
                    coll = coll.OrderBy(c => c.CollectionDate2);
                    break;
                case "date_desc":
                    coll = coll.OrderByDescending(c => c.CollectionDate2);
                    break;
                default:
                    coll = coll.OrderBy(c => c.BillNum);
                    break;
            }

            return View(coll.ToPagedList(pageNumber, pageSize));
        }


        // GET: AmountCollectionTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmountCollectionTable amountCollectionTable = db.AmountCollectionTables.Find(id);
            if (amountCollectionTable == null)
            {
                return HttpNotFound();
            }
            return View(amountCollectionTable);
        }

        // GET: AmountCollectionTables/Create
        public ActionResult Create()
        {
            ViewBag.AgentCode = new SelectList(db.AgentDetailsTables, "AgentCode", "AgentCode");
            ViewBag.EmpID = new SelectList(db.EmployeeTables, "ID", "EmployeeName");
            ViewBag.CustomerID = new SelectList(db.CustomerDetailsTables, "ID", "CustomerName");
            return View();
        }

        // POST: AmountCollectionTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,EmpID,AgentCode,CustomerID,CollectionAmount,BillNum,BillBookNum,CollectionDate,CollectionSource,CollectionDate2")] AmountCollectionTable amountCollectionTable)
        {
            if (ModelState.IsValid)
            {
                db.AmountCollectionTables.Add(amountCollectionTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AgentCode = new SelectList(db.AgentDetailsTables, "AgentCode", "AgentCode", amountCollectionTable.AgentCode);
            ViewBag.EmpID = new SelectList(db.EmployeeTables, "ID", "EmployeeName", amountCollectionTable.EmpID);
            ViewBag.CustomerID = new SelectList(db.CustomerDetailsTables, "ID", "CustomerName", amountCollectionTable.CustomerID);
            return View(amountCollectionTable);
        }

        // GET: AmountCollectionTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmountCollectionTable amountCollectionTable = db.AmountCollectionTables.Find(id);
            if (amountCollectionTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.AgentCode = new SelectList(db.AgentDetailsTables, "AgentCode", "AgentCode", amountCollectionTable.AgentCode);
            ViewBag.EmpID = new SelectList(db.EmployeeTables, "ID", "EmployeeName", amountCollectionTable.EmpID);
            ViewBag.CustomerID = new SelectList(db.CustomerDetailsTables, "ID", "CustomerName", amountCollectionTable.CustomerID);
            return View(amountCollectionTable);
        }

        // POST: AmountCollectionTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,EmpID,AgentCode,CustomerID,CollectionAmount,BillNum,BillBookNum,CollectionDate,CollectionSource,CollectionDate2")] AmountCollectionTable amountCollectionTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(amountCollectionTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AgentCode = new SelectList(db.AgentDetailsTables, "AgentCode", "AgentCode", amountCollectionTable.AgentCode);
            ViewBag.EmpID = new SelectList(db.EmployeeTables, "ID", "EmployeeName", amountCollectionTable.EmpID);
            ViewBag.CustomerID = new SelectList(db.CustomerDetailsTables, "ID", "CustomerName", amountCollectionTable.CustomerID);
            return View(amountCollectionTable);
        }

        // GET: AmountCollectionTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmountCollectionTable amountCollectionTable = db.AmountCollectionTables.Find(id);
            if (amountCollectionTable == null)
            {
                return HttpNotFound();
            }
            return View(amountCollectionTable);
        }

        // POST: AmountCollectionTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AmountCollectionTable amountCollectionTable = db.AmountCollectionTables.Find(id);
            db.AmountCollectionTables.Remove(amountCollectionTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ActvCloudSuite/ActvMvcClient/Views/AmountCollectionTables/Create.cshtml
@model ActvMvcClient.Models.AmountCollectionTable

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AmountCollectionTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmpID, "EmpID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmpID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentCode, "AgentCode", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AgentCode", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AgentCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollectionAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollectionAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollectionAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillBookNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillBookNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillBookNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollectionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollectionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollectionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollectionSource, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollectionSource, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollectionSource, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollectionDate2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollectionDate2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollectionDate2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ActvCloudSuite/ActvMvcClient/Views/AmountCollectionTables/Delete.cshtml
@model ActvMvcClient.Models.AmountCollectionTable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AmountCollectionTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CollectionAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollectionAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillBookNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillBookNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollectionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollectionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollectionSource)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollectionSource)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollectionDate2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollectionDate2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgentDetailsTable.AgentCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgentDetailsTable.AgentCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeTable.EmployeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeTable.EmployeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerDetailsTable.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerDetailsTable.CustomerName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ActvCloudSuite/ActvMvcClient/Views/AmountCollectionTables/Details.cshtml
@model ActvMvcClient.Models.AmountCollectionTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AmountCollectionTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CollectionAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollectionAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillBookNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillBookNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollectionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollectionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollectionSource)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollectionSource)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollectionDate2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollectionDate2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgentDetailsTable.AgentCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgentDetailsTable.AgentCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeTable.EmployeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeTable.EmployeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerDetailsTable.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerDetailsTable.CustomerName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ActvCloudSuite/ActvMvcClient/Views/AmountCollectionTables/Edit.cshtml
@model ActvMvcClient.Models.AmountCollectionTable

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AmountCollectionTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.EmpID, "EmpID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmpID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentCode, "AgentCode", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AgentCode", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AgentCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollectionAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollectionAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollectionAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillBookNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillBookNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillBookNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollectionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollectionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollectionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollectionSource, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollectionSource, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollectionSource, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollectionDate2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollectionDate2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollectionDate2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ActvCloudSuite/ActvMvcClient/Views/AmountCollectionTables/Index.cshtml
@using PagedList.Mvc;

@model PagedList.IPagedList<ActvMvcClient.Models.AmountCollectionTable>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Mobile Collection";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<h2>Mobile Collection</h2>

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Delete Duplicate Mobile Entries", "RemoveDuplicateMobileCollectionEntriesIndex", "MobileCollections")</li>
    </ul>
</div>
<br/>

@using (Html.BeginForm("Index", "AmountCollectionTables", FormMethod.Post))
{
    <p>
        <label for="from">From</label>
        @Html.TextBox("from")
        <label for="to">To</label>
        @Html.TextBox("to")
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            BillNum
        </th>
        <th>
            Collection Amount
        </th>
        <th>
            @Html.ActionLink("Collection Date", "Index", new
       {
           sortOrder = ViewBag.DateSortParm,
           currentFilter = ViewBag.CurrentFilter
       })
        </th>
        <th>
            Agent Code
        </th>
        <th>
            Employee Name
        </th>
        <th>
            @Html.ActionLink("Customer ID", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Customer Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BillNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CollectionAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CollectionDate2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AgentDetailsTable.AgentCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeTable.EmployeeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerDetailsTable.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerDetailsTable.CustomerName)
        </td>        
    </tr>
}

</table>
<br/>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

<script>
    $(function () {
        $("#from").datepicker({
            defaultDate: "+1w",
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 2,
            dateFormat: "dd/mm/yy",
            onClose: function (selectedDate) {
                $("#to").datepicker("option", "minDate", selectedDate);
            }
        });
        $("#to").datepicker({
            defaultDate: "+1w",
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 2,
            dateFormat: "dd/mm/yy",
            onClose: function (selectedDate) {
                $("#from").datepicker("option", "maxDate", selectedDate);
            }
        });
    });
</script>