ActvCloudSuite/ActvMvcClient/Controllers/CompanyTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ActvMvcClient.Models;
using ActvMvcClient.DynamicTableModels;
using System.Configuration;
using System.Threading.Tasks;

namespace ActvMvcClient.Controllers
{
    [Authorize]
    public class CompanyTablesController : Controller
    {
        private ActvMvcClientEntities db = new ActvMvcClientEntities();
        private ActvMvcClientEntities newdb;
        private int taskId = 24;
        private static int progressVar;

        // GET: CompanyTables
        public ActionResult Index()
        {
            var companyTables = db.CompanyTables.Include(c => c.CompanyDetail);
            return View(companyTables.ToList());
        }

        // GET: CompanyTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyTable companyTable = db.CompanyTables.Find(id);
            if (companyTable == null)
            {
                return HttpNotFound();
            }
            return View(companyTable);
        }

        // GET: CompanyTables/Create
        public ActionResult Create()
        {
            ViewBag.CompanyId = new SelectList(db.CompanyDetails, "Id", "CompanyName");
            ViewBag.Error = "";
            return View();
        }

        // POST: CompanyTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [NoAsyncTimeout]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CompanyName,FinancialYear,StartMonth,EndMonth,LastUpdateDate,CompanyId")] CompanyTable companyTable)
        {
            newdb = new ActvMvcClientEntities();
            if (ModelState.IsValid)
            {


                if (!IsYearExistForCompany(companyTable.CompanyId, companyTable.FinancialYear))
                {

                    //Do work here
                    companyTable.StartMonth = 1;
                    companyTable.EndMonth = 12;
                    companyTable.CompanyName = newdb.CompanyDetails.FirstOrDefault(c => c.Id == companyTable.CompanyId).CompanyName;
                    companyTable.LastUpdateDate = DateTime.Today.ToString("dd/MM/yyyy");
                    newdb.CompanyTables.Add(companyTable);
                    newdb.SaveChanges();
                    LedgerTable ledgerTable = new LedgerTable(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString);
                    ledgerTable.CreateLedgerTable(companyTable);
                    InsertCustomerIntoNewLedger(ledgerTable, companyTable);
                    //return RedirectToAction("Index");
                    newdb.SaveChanges();
                    ViewBag.CompanyId = new SelectList(newdb.CompanyDetails, "Id", "CompanyName", companyTable.CompanyId);
                    return View();
                }
                else
                {
                    //Display Error that Year already exist
                    ViewBag.Error = "Year already exist, please enter correct value.";
                    ViewBag.CompanyId = new SelectList(newdb.CompanyDetails, "Id", "CompanyName", companyTable.CompanyId);
                    return View(companyTable);
                }
            }

            ViewBag.CompanyId = new SelectList(newdb.CompanyDetails, "Id", "CompanyName", companyTable.CompanyId);
            //return View(companyTable);
            return View();
        }

        public ActionResult CreateCompleted(string result)
        {
            return View();
        }

        public ActionResult CreateProgress()
        {
            //Report progress
            HttpContext.Application["task" + taskId] = progressVar;
            return Json(new
            {
                Progress = HttpContext.Application["task" + taskId].ToString()
            }, JsonRequestBehavior.AllowGet);
        }


        private void InsertCustomerIntoNewLedger(LedgerTable ledgerTable, CompanyTable company)
        {
            //Insert all the customers into newly created ledger table.
            //Go through each customers in CustomerTable, Check the customer exist in Previous year table. If exist, update currenty year ledger with OldBalance, TotalBalance
            LedgerTable prevYearLedgerTable = new LedgerTable(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString);
            int prevYear = int.Parse(company.FinancialYear) - 1;
            prevYearLedgerTable.TableName = prevYearLedgerTable.GetLedgerTableNameForYear(company.GetPreviousYearCompany());
            bool prevYearLedgerExist = false;
            prevYearLedgerExist = prevYearLedgerTable.IsTableExist(prevYearLedgerTable.TableName);
            double progress = 0.0;
            foreach (CustomerDetailsTable customer in newdb.CustomerDetailsTables)
            {
                progress++;
                //Report progress
                progressVar = Convert.ToInt32((progress / newdb.CustomerDetailsTables.Count()) * 100);

                ledgerTable.InitLedgerToDefaultValues();
                ledgerTable.CustID = customer.ID;
                ledgerTable.CustCode = customer.CustomerCode;
                ledgerTable.AgentCode = customer.AgentCode;
                ledgerTable.AreaCode = customer.AreaCode;
                ledgerTable.OldBalance = customer.InitialBalance;
                ledgerTable.TotalBalance = customer.InitialBalance;
                
                if (prevYearLedgerExist)
                {
                    prevYearLedgerTable.GetCustomerLedger(customer.ID);

                    //billNumber = prevYearLedgerTable.Bill[12];
                    //billDate = prevYearLedgerTable.Date[12];
                    //billAmount = prevYearLedgerTable.Amt[12];

                    ledgerTable.OldBalance = prevYearLedgerTable.TotalBalance;
                    ledgerTable.TotalBalance = prevYearLedgerTable.TotalBalance;
                    
                }
                ledgerTable.InsertLedgerEntry();
                //If the old balance has negative balance, the customer has paid advance amount.
                if (ledgerTable.OldBalance < 0)
                {
                    AllocateAdvanceAmount(ledgerTable.OldBalance, prevYearLedgerTable.Bill[12], prevYearLedgerTable.Amt[12], prevYearLedgerTable.Amt[12], ledgerTable);
                }
                
            }
        }

        private void AllocateAdvanceAmount(int advanceAmount, string billNumber, string billDate, string billAmount, LedgerTable ledgerTable)
        {
            if (advanceAmount < 0)
                advanceAmount *= -1;

            if (advanceAmount > 0)
            {
                InsertAmount(advanceAmount, billNumber, billDate, billAmount, ledgerTable);
            }

            ledgerTable.Update();
            //Update the customertable
            CustomerDetailsTable customer = newdb.CustomerDetailsTables.SingleOrDefault(c => c.ID == ledgerTable.CustID);
            customer.InitialBalance = ledgerTable.OldBalance;
            //newdb.SaveChanges();
        }

        private void InsertAmount(int amount, string billNumber, string billDate, string billAmount, LedgerTable ledgerTable)
        {
            int amountPaid = amount;
            int monthNum = 1;
            int monthlyBalance = ledgerTable.GetPaymentFreqAmt();
            while ((amountPaid > 0) && (monthNum < 13))
            {
                switch (monthNum++)
                {
                    case 1:
                        this.AllocateAmount(amount, ref amountPaid, 1, billNumber, billDate, billAmount, ledgerTable, monthlyBalance);
                        break;

                    case 2:
                        this.AllocateAmount(amount, ref amountPaid, 2, billNumber, billDate, billAmount, ledgerTable, monthlyBalance);
                        break;

                    case 3:
                        this.AllocateAmount(amount, ref amountPaid, 3, billNumber, billDate, billAmount, ledgerTable, monthlyBalance);
                        break;

                    case 4:
                        this.AllocateAmount(amount, ref amountPaid, 4, billNumber, billDate, billAmount, ledgerTable, monthlyBalance);
                        break;

                    case 5:
                        this.AllocateAmount(amount, ref amountPaid, 5, billNumber, billDate, billAmount, ledgerTable, monthlyBalance);
                        break;

                    case 6:
                        this.AllocateAmount(amount, ref amountPaid, 6, billNumber, billDate, billAmount, ledgerTable, monthlyBalance);
                        break;

                    case 7:
                        this.AllocateAmount(amount, ref amountPaid, 7, billNumber, billDate, billAmount, ledgerTable, monthlyBalance);
                        break;

                    case 8:
                        this.AllocateAmount(amount, ref amountPaid, 8, billNumber, billDate, billAmount, ledgerTable, monthlyBalance);
                        break;

                    case 9:
                        this.AllocateAmount(amount, ref amountPaid, 9, billNumber, billDate, billAmount, ledgerTable, monthlyBalance);
                        break;

                    case 10:
                        this.AllocateAmount(amount, ref amountPaid, 10, billNumber, billDate, billAmount, ledgerTable, monthlyBalance);
                        break;

                    case 11:
                        this.AllocateAmount(amount, ref amountPaid, 11, billNumber, billDate, billAmount, ledgerTable, monthlyBalance);
                        break;

ActvCloudSuite/ActvMvcClient/Views/CompanyTables/Create.cshtml
@model ActvMvcClient.Models.CompanyTable

@{
    ViewBag.Title = "Create Company Ledger";
}

<link href="~/css/smoothness/jquery-ui-1.9.0.custom.css" rel="stylesheet" />
<script src="~/Scripts/jquery-2.1.4.js"></script>
<script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
<script src="~/Scripts/jsrender.js"></script>

<h2>Create Company Ledger</h2>
<h3 class="text-danger">@ViewBag.Error</h3>

@using (Html.BeginForm("Create", "CompanyTables", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    @*<h2 id="progress">Progress</h2>*@

    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.FinancialYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FinancialYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FinancialYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <p>
            <input type="submit" value="Submit" id="submitButton" />

        </p>
    </div>
}



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActvCloudSuite/ActvMvcClient/Views/CompanyTables/Delete.cshtml
@model ActvMvcClient.Models.CompanyTable

@{
    ViewBag.Title = "Delete Company Ledger";
}

<h2>Delete Company Ledger</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompanyTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinancialYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinancialYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdateDate)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ActvCloudSuite/ActvMvcClient/Views/CompanyTables/Details.cshtml
@model ActvMvcClient.Models.CompanyTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CompanyTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinancialYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinancialYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyDetail.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyDetail.CompanyName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

ActvCloudSuite/ActvMvcClient/Views/CompanyTables/Edit.cshtml
@model ActvMvcClient.Models.CompanyTable

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CompanyTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FinancialYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FinancialYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FinancialYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="hidden">
            @Html.LabelFor(model => model.StartMonth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartMonth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartMonth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="hidden">
            @Html.LabelFor(model => model.EndMonth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndMonth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndMonth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="hidden">
            @Html.LabelFor(model => model.LastUpdateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastUpdateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastUpdateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="hidden">
            @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActvCloudSuite/ActvMvcClient/Views/CompanyTables/Index.cshtml
@model IEnumerable<ActvMvcClient.Models.CompanyTable>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FinancialYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartMonth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndMonth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastUpdateDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyDetail.CompanyName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FinancialYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartMonth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndMonth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastUpdateDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyDetail.CompanyName)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.ID }) 
        </td>
    </tr>
}

</table>